### ISSUE TITLE
Creating a shipment errors with customerDoc.save() not a function

### ISSUE THREAD

**Issue by joshplumley** [conturo-prototyping/pack-ship-demo#80]
It looks like all  three options are broken with the same error:

```TypeError: customerDoc.save is not a function
    at /home/josh/projects/pack-ship-demo-jp/server/src/shipment/controller.js:186:34
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async module.exports (/home/josh/projects/pack-ship-demo-jp/server/src/handler.js:9:27)```

**Comment by jarrilla** [comment]
Fixed by #83
